/** A permutation maps label i to p[i]. Labels are zero-based internally. */
export type Permutation = number[];

export type DerivedStep = {
  name: string;
  order: number;
  elements: Permutation[];
};

export type ConjugacyClass = {
  representative: Permutation;
  label: string;
  size: number;
  elements: Permutation[];
};

const symmetricCache = new Map<number, Permutation[]>();
const derivedCache = new Map<string, Permutation[]>();
const seriesCache = new Map<number, DerivedStep[]>();
const normalClosureCache = new Map<string, Permutation[]>();
let a5ClassesCache: ConjugacyClass[] | undefined;

const key = (p: Permutation) => p.join(",");
const copyGroup = (group: Permutation[]) => group.map((p) => [...p]);
const multiply = (a: Permutation, b: Permutation): Permutation =>
  b.map((value) => a[value]);
const sorted = (group: Permutation[]) =>
  group.sort((a, b) => {
    for (let i = 0; i < a.length; i++) {
      if (a[i] !== b[i]) return a[i] - b[i];
    }
    return 0;
  });

function requireDegree(n: number, maximum = Number.MAX_SAFE_INTEGER) {
  if (!Number.isSafeInteger(n) || n < 1 || n > maximum)
    throw new RangeError(`Degree must be an integer between 1 and ${maximum}.`);
}

function requirePermutation(p: Permutation) {
  if (
    !Array.isArray(p) ||
    p.length === 0 ||
    new Set(p).size !== p.length ||
    !p.every(
      (value) => Number.isInteger(value) && value >= 0 && value < p.length,
    )
  )
    throw new RangeError(
      "A permutation must contain each label 0, …, n−1 once.",
    );
}

function requirePair(a: Permutation, b: Permutation) {
  requirePermutation(a);
  requirePermutation(b);
  if (a.length !== b.length)
    throw new RangeError("Permutations must act on the same number of labels.");
}

export function identity(n: number): Permutation {
  requireDegree(n);
  return Array.from({ length: n }, (_, i) => i);
}

/** compose(a, b) = a ∘ b: apply b first, then a. */
export function compose(a: Permutation, b: Permutation): Permutation {
  requirePair(a, b);
  return multiply(a, b);
}

export function inverse(p: Permutation): Permutation {
  requirePermutation(p);
  const result = new Array<number>(p.length);
  p.forEach((value, i) => {
    result[value] = i;
  });
  return result;
}

/** [a, b] = aba⁻¹b⁻¹, with the same rightmost-first composition convention. */
export function commutator(a: Permutation, b: Permutation): Permutation {
  requirePair(a, b);
  return multiply(multiply(multiply(a, b), inverse(a)), inverse(b));
}

/** Omit fixed labels; display moved labels starting at 1. */
export function cycleNotation(p: Permutation): string {
  requirePermutation(p);
  const seen = new Set<number>();
  const cycles: string[] = [];
  for (let start = 0; start < p.length; start++) {
    if (seen.has(start)) continue;
    const cycle: number[] = [];
    let next = start;
    while (!seen.has(next)) {
      seen.add(next);
      cycle.push(next + 1);
      next = p[next];
    }
    if (cycle.length > 1) cycles.push(`(${cycle.join(" ")})`);
  }
  return cycles.join("") || "e";
}

export function parity(p: Permutation): 1 | -1 {
  requirePermutation(p);
  let sign: 1 | -1 = 1;
  for (let i = 0; i < p.length; i++)
    for (let j = i + 1; j < p.length; j++)
      if (p[i] > p[j]) sign = sign === 1 ? -1 : 1;
  return sign;
}

/** Enumerating beyond S5 is deliberately excluded from the browser experiment. */
export function symmetricGroup(n: number): Permutation[] {
  requireDegree(n, 5);
  let cached = symmetricCache.get(n);
  if (!cached) {
    const result: Permutation[] = [];
    const visit = (prefix: number[], remaining: number[]) => {
      if (remaining.length === 0) {
        result.push(prefix);
        return;
      }
      remaining.forEach((label, index) =>
        visit(
          [...prefix, label],
          remaining.filter((_, i) => i !== index),
        ),
      );
    };
    visit([], identity(n));
    cached = result;
    symmetricCache.set(n, cached);
  }
  return copyGroup(cached);
}

/** Right multiplication by generators explores their entire finite subgroup. */
function generatedSubgroup(generators: Permutation[], degree: number) {
  const first = identity(degree);
  const elements = [first];
  const seen = new Set([key(first)]);
  for (let cursor = 0; cursor < elements.length; cursor++) {
    for (const generator of generators) {
      const candidate = multiply(elements[cursor], generator);
      const candidateKey = key(candidate);
      if (!seen.has(candidateKey)) {
        seen.add(candidateKey);
        elements.push(candidate);
      }
    }
  }
  return sorted(elements);
}

/** Compute the subgroup generated by all commutators, not just their set. */
export function derivedSubgroup(group: Permutation[]): Permutation[] {
  if (!Array.isArray(group) || group.length === 0)
    throw new RangeError("A finite group must be nonempty.");
  group.forEach(requirePermutation);
  const degree = group[0].length;
  if (group.some((p) => p.length !== degree))
    throw new RangeError("All group elements must have the same degree.");
  const ordered = sorted(copyGroup(group));
  const keys = new Set(ordered.map(key));
  if (keys.size !== group.length || !keys.has(key(identity(degree))))
    throw new RangeError(
      "Group elements must be distinct and include identity.",
    );
  const cacheKey = ordered.map(key).join(";");
  const cached = derivedCache.get(cacheKey);
  if (cached) return copyGroup(cached);

  const inverses = ordered.map(inverse);
  const generators = new Map<string, Permutation>();
  for (let i = 0; i < ordered.length; i++) {
    for (let j = 0; j < ordered.length; j++) {
      const product = multiply(ordered[i], ordered[j]);
      if (!keys.has(key(product)))
        throw new RangeError("The supplied elements must form a closed group.");
      const value = multiply(multiply(product, inverses[i]), inverses[j]);
      generators.set(key(value), value);
    }
  }
  const result = generatedSubgroup([...generators.values()], degree);
  derivedCache.set(cacheKey, result);
  return copyGroup(result);
}

/** Include one repeated nontrivial term, making S5 → A5 → A5 visible. */
export function derivedSeries(n: number): DerivedStep[] {
  requireDegree(n, 5);
  let cached = seriesCache.get(n);
  if (!cached) {
    let group = symmetricGroup(n);
    const steps: DerivedStep[] = [];
    while (true) {
      const name =
        group.length === 1
          ? "{e}"
          : steps.length === 0
            ? `S${n}`
            : n === 4 && group.length === 4
              ? "V4"
              : `A${n}`;
      steps.push({ name, order: group.length, elements: group });
      if (
        group.length === 1 ||
        (steps.length > 1 && group.length === steps[steps.length - 2].order)
      )
        break;
      group = derivedSubgroup(group);
    }
    cached = steps;
    seriesCache.set(n, cached);
  }
  return cached.map((step) => ({
    ...step,
    elements: copyGroup(step.elements),
  }));
}

function alternatingGroup5() {
  return symmetricGroup(5).filter((p) => parity(p) === 1);
}

/** A5 has classes of sizes 1, 15, 20, 12, 12 in this display order. */
export function conjugacyClassesA5(): ConjugacyClass[] {
  if (!a5ClassesCache) {
    const group = alternatingGroup5();
    const inverses = group.map(inverse);
    const unseen = new Set(group.map(key));
    const classes: ConjugacyClass[] = [];
    for (const p of group) {
      if (!unseen.has(key(p))) continue;
      const conjugates = new Map<string, Permutation>();
      group.forEach((g, i) => {
        const conjugate = multiply(multiply(g, p), inverses[i]);
        conjugates.set(key(conjugate), conjugate);
        unseen.delete(key(conjugate));
      });
      const elements = sorted([...conjugates.values()]);
      classes.push({
        representative: elements[0],
        label: cycleNotation(elements[0]),
        size: elements.length,
        elements,
      });
    }
    const displayRank: Record<number, number> = { 1: 0, 15: 1, 20: 2, 12: 3 };
    a5ClassesCache = classes.sort(
      (a, b) => displayRank[a.size] - displayRank[b.size],
    );
  }
  return a5ClassesCache.map((entry) => ({
    ...entry,
    representative: [...entry.representative],
    elements: copyGroup(entry.elements),
  }));
}

/** The normal closure is generated by every A5 conjugate of p. */
export function normalClosureInA5(p: Permutation): Permutation[] {
  requirePermutation(p);
  if (p.length !== 5 || parity(p) !== 1)
    throw new RangeError(
      "Normal closure in A5 requires an even permutation of five labels.",
    );
  const pKey = key(p);
  let cached = normalClosureCache.get(pKey);
  if (!cached) {
    const conjugacyClass = conjugacyClassesA5().find((entry) =>
      entry.elements.some((element) => key(element) === pKey),
    )!;
    cached = generatedSubgroup(conjugacyClass.elements, 5);
    // Conjugate elements generate the same normal closure.
    conjugacyClass.elements.forEach((element) =>
      normalClosureCache.set(key(element), cached!),
    );
  }
  return copyGroup(cached);
}

/** Embed in S_n by fixing all additional labels; no factorial enumeration. */
export function extendPermutation(p: Permutation, n: number): Permutation {
  requirePermutation(p);
  requireDegree(n);
  if (n < p.length)
    throw new RangeError("An extension cannot remove existing labels.");
  return [
    ...p,
    ...Array.from({ length: n - p.length }, (_, i) => p.length + i),
  ];
}
